### ISSUE TITLE
The Meta-charset attribute must always equal "utf-8" (case-insensitive)

### ISSUE THREAD

**Issue by binyamin** [rehypejs/rehype-minify#46]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-minify-enumerated-attribute@4.1.0

### Steps to reproduce

Run the following code, modifying for your environment as necessary
```js
import { unified } from 'https://esm.sh/unified@10.1.2';
import rehypeParse from 'https://esm.sh/rehype-parse@8.0.4';
import rehypeStringify from 'https://esm.sh/rehype-stringify@9.0.3';
import rehypeMinifyEnumAttributes from 'https://esm.sh/rehype-minify-enumerated-attribute@4.1.0'

const file = await unified()
	.use(rehypeParse)
	.use(rehypeMinifyEnumAttributes)
	.use(rehypeStringify)
	.process('<meta charset="utf-8" />');
console.log(file.toString()); // output is `...<meta charset="utf8">...`
```

### Expected behavior

According to the WHATWG's HTML Living Standard, the charset attribute must be <q cite="https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset">an ASCII case-insensitive match for the string `"utf-8"`.</q> ([source](
https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset)). The [W3 HTML validator](https://validator.w3.org/nu/) accordingly produces errors.

Therefore, expected behavior is that, when the charset attribute exists on a meta element, its value is either coerced to a valid value, or at least _not_ coerced to "utf8" (no space).

### Actual behavior

`UTF-8` becomes `utf8`, probably because it's the shortest string defined in `schema.js`.

### Runtime

Deno

### OS

Linux

**Comment by wooorm** [comment]
Hi Binyamin! You’re right that the spec says that. However, that’s more of a section on how people should write HTML (sometimes the spec is a bit unclear about them).
There are different actual labels that browsers must support: https://encoding.spec.whatwg.org/#names-and-labels. `utf8` is the shortest one of that group. See here for how those groups (and more) are supported: 

https://github.com/rehypejs/rehype-minify/blob/1dc9280c341087a40dfaa332792c095f96d41686/packages/html-enumerated-attributes/index.js#L69

This project in many places uses these “leniencies” in the HTML spec to create “parse errors” and other things that linters would warn about, while the HTML spec in other places defines exactly how those errors/warnings *must* be handled by browsers.

In this case,
- extracting the encoding in the HTML spec is defined here: https://html.spec.whatwg.org/multipage/urls-and-fetching.html#extracting-character-encodings-from-meta-elements
- which links to the algorithm for “getting an encoding” is in the encoding spec I linked before, which supports `utf8`: https://encoding.spec.whatwg.org/#concept-encoding-get.

Closing as intentional, let me know if you have further questions!

**Comment by binyamin** [comment]
@wooorm That makes sense. However, it seems only fair that "utf-8" should be preserved as it is, at least via an option. It only adds one character, and it encourages best practices. It's "more correct", I guess.

**Comment by wooorm** [comment]
- There are many cases where “only one character” is exactly what this project shaves off!
- “conformant”, to what? There are many cases where this project generates HTML that the w3c validator does not appreciate, so this project isn’t conformant to that. I’d argue that this project is conformant to HTML: all the things that this project does are strongly defined in the HTML spec on how to handle them
